### ISSUE TITLE
$http.get(...).success is not a function angular 1.6

### ISSUE THREAD

**Issue by okosowski** [alexcrack/angular-ui-notification#106]
with angular `v1.6.0-rc.0`, any use Notification throw
```
TypeError: $http.get(...).success is not a function
```

**Comment by cklemming** [comment]
Yes, in Angular 1.6 the `$http Success/Error` callback methods have been dDeprecated.

They should be replaced by `.then(...)` everywhere in this library.

**Comment by celsomtrindade** [comment]
Besides this change (`.then()`) 

    line 56
    $http.get(args.template,{cache: $templateCache}).then(function(template) {

    line 189
    }, function(data){


I'm also facing some issues related to `jqLite` when usin `.bind()`. Around this line:

    line 126
    if (args.closeOnClick) {
        templateElement.addClass('clickable');
        templateElement.bind('click', closeEvent);
    }

**Comment by MikhailRoot** [comment]
https://github.com/MikhailRoot/angular-ui-notification working with angular 1.6  also I've added direct templateCache loading if we load default template which is present in ui-notification module.

**Comment by teklakct** [comment]
As @cklemming says, *in Angular 1.6 `$http Success/Error` callback methods have been deprecated.*

> *$http's deprecated custom callback methods - `success()` and `error()` - have been removed (...) but **note** that the method signatures and **return values** are **different**.*
> 
> Due to [b54a39](https://github.com/angular/angular.js/commit/b54a39e2029005e0572fbd2ac0e8f6a4e5d69014)

You should find more info in about changes with **$http** in [migration guide](https://docs.angularjs.org/guide/migration#migrate1.5to1.6-ng-services-$http).

**Comment by cropcrop** [comment]
@alexcrack Any chance @MikhailRoot 's solution will be merged? It would be great to have this callbacks deprecation fixed soon, as many angular projects are broken after upgrading to angular 1.5.9+

**Comment by MikhailRoot** [comment]
Hi ! i've updated bower.json to resolve properly for angular 1.5.x and 1.6 of package so untill our PR will be merged to master you can specify fork with fixes in your bower.json file with this line:

    "angular-ui-notification": "MikhailRoot/angular-ui-notification#0.3.4",

in your `dependencies` section.

**Comment by cropcrop** [comment]
Great! Thank you @MikhailRoot

**Comment by interruptr** [comment]
@MikhailRoot Do you not get the "Template (http://**path**.html) could not be loaded. TypeError: element.addEventListener is not a function" error?

**Comment by MikhailRoot** [comment]
@interruptr  this exception is Thrown in code just like in previous versions, if Notification service can't access  template neither from templateCache nor from $http. Also what do you mean by `http://path.html` as  path to your template. There are some points to consider:
1. Do you preload your template into template cache? (with nghtml2js or something like that)
2. Do you use this module in Cordova\PhoneGap app?  - if so - I found the best approach is to use preloaded into templateCache templates, and specifying path's to them like `/templates/yourtemplate.html`
3. May be I'm wrong but in general it's not a good idea to try to get template from fully qualified url like you've provided in example. At least i've never seen this in code. If you are developing website you can specify relative path(better starting from forward slash like `/partials/templatename.html` ), but much better - use templateCache with preloaded templates -  with this approach you'll overcome a lot of troubles with relative paths of your app and templates.

**Comment by interruptr** [comment]
I require it with webpack and insert the template into template cache. I found a workaround for this - if I add a template into templateCache with the name of the default template ("angular-ui-notification.html") then it works. Otherwise the error described above gets thrown... It's quite interesting. I will look into the issue a bit later.

**Comment by MikhailRoot** [comment]
@interruptr  Thank you for investigation and insight, i've updated code to check templateCache first both default and custom specified template names. 
Latest fixes with update in bower.json

`"angular-ui-notification": "MikhailRoot/angular-ui-notification#0.3.5"`

then `bower update`

**Comment by tonylampada** [comment]
I've submitted #109 just in the case @alexcrack is in a hurry and can't ind the time to give the deserved attention to @MikhailRoot 's #108

**Comment by bhaveshvyas007** [comment]
Please fix this asap...

**Comment by MikhailRoot** [comment]
@bhaveshvyas007  as i mentioned above untill fixed or merged use

 `"angular-ui-notification": "MikhailRoot/angular-ui-notification#0.3.5"` 

in your bower.json then update. works with angular 1.6

**Comment by jebberwocky** [comment]
@MikhailRoot guess that we need to use your branch for now

**Comment by alexcrack** [comment]
Merged @MikhailRoot's pull-request.
